# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=b'created at')),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
