# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160122_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(default=b'string', max_length=200),
        ),
    ]
